### ISSUE TITLE
Consider renaming repo or splitting `warehouse` sub-repo 

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/esgfpub#104]
https://github.com/E3SM-Project/esgfpub/pull/97#issuecomment-1050262215

> Another alternative is to separate the warehouse directory from the esgfpub repo in a new e3sm_warehouse repo. I recall Sterling saying like "it probably should be in its own repo but I added it here" or something to that effect.

https://github.com/E3SM-Project/esgfpub/pull/97#issuecomment-1050395831

> I am also leaning towards starting a new repo called e3sm_warehouse. I can actually make a copy of this repo as the starting point of the e3sm_warehouse repo, and just delete the /esgfpub directory there. Then we can archive the esgfpub repo if it is no longer being used.
> 
> As Jill mentioned, I would make a branch in this repo and continue working as needed (please no more work on master!). There are ways to move branches between repositories: https://stackoverflow.com/questions/34384642/how-to-copy-a-branch-from-one-github-repository-to-another

**Comment by chengzhuzhang** [comment]
Hey Tom, I'm in support of splitting `warehouse`, so that the new-repo, has a cleanly defined goal and more streamlined execution, devOps, structure and docs. Another possibility is to simply rename this repo and also make the structural changes here? The advantage to keep using this repo is that we get to retain all the repo history and issues/PR records. What do you think?

**Comment by tomvothecoder** [comment]
Hi Jill, that's another viable option that would minimize dev disruption and reduce effort compared to splitting repos.

What we can do if we follow this path:
1. Rename repository to `e3sm_warehouse` (`warehouse` is too generic for a Python package name)
2. Rename modules and directories to `e3sm_warehouse` 
3. Remove `esgfpub` directory 
   - This directory will still exist in the Git history, in case we ever need to restore or reference it

I'm thinking that your suggested path is the way forward, but I'll do a bit more research before we finalize this decision.
I'll also make sure to loop @TonyB9000 in.

**Comment by TonyB9000** [comment]
I will totally agree with whatever you guys decide.  I only need to know when I need to change my routine.  If paths and environments change names, I imagine I will need to adjust.  I may/may-not need to "clone" a new (e3sm_)warehouse, etc.

**Comment by tomvothecoder** [comment]
Hey @rljacob, can you make me an admin for this repo?

**Comment by rljacob** [comment]
Done.

**Comment by tomvothecoder** [comment]
Thanks @rljacob!
