### ISSUE TITLE
GenerateMapfile Job implementation

### ISSUE THREAD

**Issue by sterlingbaldwin** [E3SM-Project/esgfpub#25]
The GenerateMapfile job needs to be implemented.

**Comment by TonyB9000** [comment]
pushed (scripts)/esgmapfile_make.sh, and (jobs)/generatemapfile.py

**Comment by sterlingbaldwin** [comment]
For the python3 mapfile generator see: https://github.com/E3SM-Project/esgfpub/blob/publication/warehouse/warehouse/scripts/generate_mapfile.py

**Comment by TonyB9000** [comment]
For some reason, I cannot seem to add comment to either of the web pages included below.

Just to confirm:

help="Output path for the mapfile including the file name, "

"by default it will be named <dataset_id>.map and be placed "
"in the current working directory.")

By default, NOT <dataset_id>.<version_number>.map

____tony____
