### ISSUE TITLE
Unify Timestamp Format

### ISSUE THREAD

**Issue by TonyB9000** [E3SM-Project/esgfpub#78]
Disparate timestamp formats employed in logfile entries, dataset status file entries, and logfile names interfere with uniform data processing and proper time-sorting of events.  In particular, occasional appearances of the format "YYYY/MM/DD hh:mm:ss" and its variants, intended primarily for human consumption, break the proper sorting of entries and introduce characters that limit the utility of these timestamps in alternate settings, requiring unneeded quoting or character escapes in handling.

The safest and most compact timestamp format (while still providing human readability) is "YYYYMMDD_hhmmss", and where subseconds are needed to ensure fine-grained time-sorting is available, the extended "YYYYMMDD_hhmmss_subseconds" can be employed.  This introduces only the  underscore ("_") as a non-numeric character, and is safe to use in most all of our data-processing applications.

Additionally, the short (YYYYMMDD_hhmmss) and long (YYYYMMDD_hhmmss_subseconds) versions of these timestamps collate together properly, as demonstrated here:

-rw-rw-r--. 1 bartoletti1 publishers 0 Aug 23 09:24 afile-20210815_123456
-rw-rw-r--. 1 bartoletti1 publishers 0 Aug 23 09:24 afile-20210815_123457
-rw-rw-r--. 1 bartoletti1 publishers 0 Aug 23 09:24 afile-20210815_123457_555555
-rw-rw-r--. 1 bartoletti1 publishers 0 Aug 23 09:24 afile-20210815_123458

Thus, there is no need to convert previous "YYYYMMDD_hhmmss" to "YYYYMMDD_hhmmss_000000" in order to ensure proper sorting of historical entries.

The proposal here is to ensure our warehouse codes employ this uniform timestamp everywhere, and to convert data process files (logs and status files) to this format.

**Comment by rljacob** [comment]
Why not use the ISO standard for a date-time string?  https://en.wikipedia.org/wiki/ISO_8601

**Comment by TonyB9000** [comment]
As a timestamp in isolation, or for human consumption, the ISO standard is unambiguous and very informative.  It actually specifies a range of formats for conveying various information (day of week, etc).  The one I use is nominally the ISO calendar date YYYYMMDD, followed by the ISO time Thhmmss.sss, but replacing the "T' separator with an underscore for improved readability (in my opinion), and replacing the period marking the subseconds with another underscore to avoid conflict with the period we use as a primary delimiter in other contexts.  I was considering adding a terminal 'Z' to announce "This is UTC Zulu", but hope to use this timezone everywhere.  If other want to indicate another timezone (PST, PDT, etc) let it be added, but have its absence indicate Z.

I think 20210815_112045 is easier on the eyes than is 20210815T112045.  Both are very compact and arguably the latter frees up use of the underscore as a critical delimiter.  I could be convinced to go there.  Presently, the underscore is our "least significant delimiting character". If we ever count-off field position by underscore, it is among the innermost of the parsing (as we have adopted "realm_grid_freq" as a token for dataset subtype).  But we parse-by-period near the top of contexts such as the dataset_id, and so embedding a period in the timestamp (to mark off sub-seconds) could lead to issues.  The simple YYYYMMDD_hhmmss_subsecs is optimally compact and ordered while allowing human-parsing.

I was a bit disappointed when I learned that V2 would employ periods within experiment names.  Presently, we replace "model version" 1.1.ECA with 1_1_ECA for the ESGF database use of period in the dataset_id.  We will need to conduct a similar operation for experiment names, for the same reason.

**Comment by thorntonpe** [comment]
Just a vote for the ISO 8601 format with T and Z, e.g. 20210824T150025Z, and a further vote to have all (data) times used within the project to be expressed in UTC. Are there cases where a data time needs to be in another time zone?

**Comment by TonyB9000** [comment]
Totally agree with UTC everywhere (I can't imagine why another or local time zone would be required).  For our state machine we need to timestamp events/outcomes to subseconds (millisecs, or better).  And I'd want to avoid introducing a decimal (.) in the format.

One issue is that for some applications we need to employ the python "logging" module, and using it I can get as close as

20210824T150025_123Z  (msecs are supported, here as (msecs)03d).

I can sub-msec with  (msecs)03f, but this introduces the decimal, as in

20210824T150025_123.456Z

And I'd like to avoid introducing custom formatter classes to elide the "."

Too bad  ISO 8601 does not support something like (date)T(time)t(fractionalseconds).

**Comment by chengzhuzhang** [comment]
resolved by #81
